version: 3
jobs:
  build:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:6f:38:96:a7:71:ee:ad:08:c9:e0:27:90:b3:56:b7"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s /src -d /src/public
      - run:
          name: test the generated html files
          command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - deploy:
          name: push to master branch
          command: sh deploy.sh